import type { SpecDefinitionSeed } from "@versus-engine/shared";

/**
 * Full SpecDefinition catalogs for the categories demo data ships with
 * (CLAUDE.md "Data conventions": 4 cars, 4 phones, 2 laptops so demos work
 * out of the box). The "cars" set intentionally mirrors the rounds in
 * examples/comparison-example.json so seeding the video payload and seeding
 * this catalog upsert the same rows instead of creating duplicates.
 */
export const CAR_SPEC_DEFINITIONS: SpecDefinitionSeed[] = [
  {
    key: "horsepower",
    label: "Horsepower",
    unit: "hp",
    dataType: "NUMBER",
    higherIsBetter: true,
    visualization: "BAR",
    displayFormat: "{value} hp",
    icon: "zap",
    priorityWeight: 1.2,
    sortOrder: 0,
  },
  {
    key: "0_100_km_h",
    label: "0–100 km/h",
    unit: "s",
    dataType: "NUMBER",
    higherIsBetter: false,
    visualization: "COUNTER",
    displayFormat: "{value} s",
    icon: "timer",
    priorityWeight: 1.2,
    sortOrder: 1,
  },
  {
    key: "drivetrain",
    label: "Drivetrain",
    unit: null,
    dataType: "TEXT",
    higherIsBetter: true,
    visualization: "BADGE",
    displayFormat: null,
    icon: "cog",
    priorityWeight: 0.8,
    sortOrder: 2,
  },
  {
    key: "torque",
    label: "Torque",
    unit: "Nm",
    dataType: "NUMBER",
    higherIsBetter: true,
    visualization: "GAUGE",
    displayFormat: "{value} Nm",
    icon: "gauge",
    priorityWeight: 1.0,
    sortOrder: 3,
  },
  {
    key: "weight",
    label: "Weight",
    unit: "kg",
    dataType: "NUMBER",
    higherIsBetter: false,
    visualization: "BAR",
    displayFormat: "{value} kg",
    icon: "scale",
    priorityWeight: 0.8,
    sortOrder: 4,
  },
  {
    key: "price",
    label: "Price",
    unit: "USD",
    dataType: "NUMBER",
    higherIsBetter: false,
    visualization: "BAR",
    displayFormat: "${value}",
    icon: "dollar-sign",
    priorityWeight: 1.5,
    sortOrder: 5,
  },
  {
    key: "top_speed",
    label: "Top Speed",
    unit: "km/h",
    dataType: "NUMBER",
    higherIsBetter: true,
    visualization: "BAR",
    displayFormat: "{value} km/h",
    icon: "gauge-circle",
    priorityWeight: 0.7,
    sortOrder: 6,
  },
];

export const PHONE_SPEC_DEFINITIONS: SpecDefinitionSeed[] = [
  {
    key: "price",
    label: "Price",
    unit: "USD",
    dataType: "NUMBER",
    higherIsBetter: false,
    visualization: "BAR",
    displayFormat: "${value}",
    icon: "dollar-sign",
    priorityWeight: 1.5,
    sortOrder: 0,
  },
  {
    key: "display_size",
    label: "Display Size",
    unit: "in",
    dataType: "NUMBER",
    higherIsBetter: true,
    visualization: "BAR",
    displayFormat: "{value}\"",
    icon: "smartphone",
    priorityWeight: 0.8,
    sortOrder: 1,
  },
  {
    key: "battery_capacity",
    label: "Battery",
    unit: "mAh",
    dataType: "NUMBER",
    higherIsBetter: true,
    visualization: "BAR",
    displayFormat: "{value} mAh",
    icon: "battery",
    priorityWeight: 1.1,
    sortOrder: 2,
  },
  {
    key: "main_camera_mp",
    label: "Main Camera",
    unit: "MP",
    dataType: "NUMBER",
    higherIsBetter: true,
    visualization: "COUNTER",
    displayFormat: "{value} MP",
    icon: "camera",
    priorityWeight: 1.0,
    sortOrder: 3,
  },
  {
    key: "ram_gb",
    label: "RAM",
    unit: "GB",
    dataType: "NUMBER",
    higherIsBetter: true,
    visualization: "GAUGE",
    displayFormat: "{value} GB",
    icon: "cpu",
    priorityWeight: 0.9,
    sortOrder: 4,
  },
  {
    key: "storage_gb",
    label: "Storage",
    unit: "GB",
    dataType: "NUMBER",
    higherIsBetter: true,
    visualization: "BAR",
    displayFormat: "{value} GB",
    icon: "hard-drive",
    priorityWeight: 0.9,
    sortOrder: 5,
  },
  {
    key: "has_5g",
    label: "5G",
    unit: null,
    dataType: "BOOLEAN",
    higherIsBetter: true,
    visualization: "BADGE",
    displayFormat: null,
    icon: "signal",
    priorityWeight: 0.6,
    sortOrder: 6,
  },
];

export const LAPTOP_SPEC_DEFINITIONS: SpecDefinitionSeed[] = [
  {
    key: "price",
    label: "Price",
    unit: "USD",
    dataType: "NUMBER",
    higherIsBetter: false,
    visualization: "BAR",
    displayFormat: "${value}",
    icon: "dollar-sign",
    priorityWeight: 1.5,
    sortOrder: 0,
  },
  {
    key: "cpu_cores",
    label: "CPU Cores",
    unit: "cores",
    dataType: "NUMBER",
    higherIsBetter: true,
    visualization: "GAUGE",
    displayFormat: "{value} cores",
    icon: "cpu",
    priorityWeight: 1.1,
    sortOrder: 1,
  },
  {
    key: "ram_gb",
    label: "RAM",
    unit: "GB",
    dataType: "NUMBER",
    higherIsBetter: true,
    visualization: "BAR",
    displayFormat: "{value} GB",
    icon: "memory-stick",
    priorityWeight: 1.0,
    sortOrder: 2,
  },
  {
    key: "storage_gb",
    label: "Storage",
    unit: "GB",
    dataType: "NUMBER",
    higherIsBetter: true,
    visualization: "BAR",
    displayFormat: "{value} GB",
    icon: "hard-drive",
    priorityWeight: 0.9,
    sortOrder: 3,
  },
  {
    key: "battery_life_hours",
    label: "Battery Life",
    unit: "h",
    dataType: "NUMBER",
    higherIsBetter: true,
    visualization: "COUNTER",
    displayFormat: "{value} h",
    icon: "battery",
    priorityWeight: 1.1,
    sortOrder: 4,
  },
  {
    key: "weight",
    label: "Weight",
    unit: "kg",
    dataType: "NUMBER",
    higherIsBetter: false,
    visualization: "BAR",
    displayFormat: "{value} kg",
    icon: "scale",
    priorityWeight: 0.7,
    sortOrder: 5,
  },
  {
    key: "display_size",
    label: "Display Size",
    unit: "in",
    dataType: "NUMBER",
    higherIsBetter: true,
    visualization: "BADGE",
    displayFormat: "{value}\"",
    icon: "laptop",
    priorityWeight: 0.6,
    sortOrder: 6,
  },
];

export const SPEC_DEFINITIONS_BY_CATEGORY: Record<string, SpecDefinitionSeed[]> = {
  cars: CAR_SPEC_DEFINITIONS,
  phones: PHONE_SPEC_DEFINITIONS,
  laptops: LAPTOP_SPEC_DEFINITIONS,
};
